# Generated by Django 4.2 on 2025-10-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_grouppost_story_video_videocomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='background_color',
            field=models.CharField(default='#000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
