# Generated by Django 4.2 on 2025-10-18 09:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_story_background_color_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grouppost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storyhighlight',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AlterField(
            model_name='group',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='group_covers'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='group_post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='story_images'),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='story_videos'),
        ),
        migrations.AlterField(
            model_name='storyhighlight',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='highlight_covers'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_thumbnails'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='videos'),
        ),
    ]
